/**
 * The AGENTS.md scaffolded into a brand-guide directory by `brandkit init`.
 *
 * It is a maintenance contract for AI agents (and humans) working in the host
 * project's brand directory: where the source of truth is, how to read the
 * brand, and — crucially — to record changes in the changelog. It is brand-
 * agnostic (it points at config.json for specifics), so it never goes stale.
 */
function agentsDoc() {
  return [
    '# Working on this brand guide (for AI agents)',
    '',
    'This directory is a **[brandkit](https://github.com/The-Stack-Lab/brandkit) brand guide**.',
    '`config.json` is the single source of truth — it drives the rendered guide (`index.html`) and',
    'the machine-readable exports below.',
    '',
    '## Read the brand from the exports, not the page',
    '',
    '- `brand.json` — full structured brand: colors (roles + contrast), typography, voice, logos, spacing',
    '- `tokens.json` — W3C design tokens (DTCG `$type`/`$value`) for code and design tooling',
    '- `brand.md` — a brief on how to stay on-brand',
    '',
    'These are regenerated by `brandkit build` / `brandkit export`. If they look stale, rebuild.',
    '',
    '## When you change the brand, record it in the changelog',
    '',
    'Whenever you edit the brand — colors, type, logos, voice, spacing, or anything in `config.json` —',
    'log what changed so the guide keeps an accurate history:',
    '',
    '```bash',
    'npx brandkit changelog "what you changed"   # e.g. "Swapped accent to teal, refreshed the logo"',
    '```',
    '',
    "This prepends an entry to `config.json`'s `changelog` and bumps `brand.version`.",
    '',
    '**Versioning:** a new guide starts at **0.1** and climbs with each change (0.1 → 0.2 → …). When',
    'the brand is finalized, lock it at **1.0**:',
    '',
    '```bash',
    'npx brandkit changelog --lock "Brand finalized"',
    '```',
    '',
    'The changelog renders on its own page (`changelog.html`) and is included in `brand.json` / `brand.md`.',
    '',
    '## Commands',
    '',
    '```bash',
    'npx brandkit dev .          # preview at http://localhost:4800 (live reload)',
    'npx brandkit build .        # build static files + exports for deploy',
    'npx brandkit export .       # regenerate brand.json / tokens.json / brand.md',
    'npx brandkit changelog "…"  # record a brand change (see above)',
    '```',
    '',
    '## Rules',
    '',
    '- Edit `config.json` — do **not** hand-edit `index.html`, `styles.css`, `engine.js`, or',
    '  `changelog.html`. They are universal and overwritten on every rebuild.',
    '- After changing `config.json`: run `brandkit changelog "…"`, then `brandkit build` (or `export`).',
    ''
  ].join('\n');
}

module.exports = { agentsDoc: agentsDoc };
