var fs = require('fs');
var path = require('path');
var exporter = require('./export');

/**
 * Build a CSS font stack from a font def. When the brand's official typeface
 * isn't web-available, an optional `fallback` web stand-in is woven in:
 *   'Family', 'Fallback', sans-serif
 * No fallback → the original 'Family', sans-serif (backward-compatible).
 */
function fontStack(font) {
  if (!font || !font.family) return 'sans-serif';
  // Strip control chars (a raw newline ends a CSS string) then escape
  // backslash + single-quote, so a config value can't break out of the quoted
  // CSS string and inject rules into the generated :root block.
  function q(s) { return String(s).replace(/[\u0000-\u001F\u007F]/g, '').replace(/[\\']/g, '\\$&'); }
  var stack = "'" + q(font.family) + "'";
  if (font.fallback) stack += ", '" + q(font.fallback) + "'";
  return stack + ', sans-serif';
}

/**
 * Generate a :root CSS block from config.theme + config.fonts.
 */
function generateRootCSS(config) {
  var lines = [':root {'];
  if (config.theme) {
    var keys = Object.keys(config.theme);
    for (var i = 0; i < keys.length; i++) {
      lines.push('  ' + keys[i] + ': ' + config.theme[keys[i]] + ';');
    }
  }
  if (config.fonts) {
    if (config.fonts.display) {
      lines.push('  --font-display: ' + fontStack(config.fonts.display) + ';');
    }
    if (config.fonts.body) {
      lines.push('  --font-body: ' + fontStack(config.fonts.body) + ';');
    }
  }
  lines.push('}');
  return lines.join('\n');
}

/**
 * Escape a string for safe interpolation inside a double-quoted HTML attribute.
 * A legitimate URL path never contains these chars, so real basePaths pass
 * through unchanged; a hostile value can't break out of the attribute.
 */
function escapeAttr(s) {
  return String(s).replace(/&/g, '&amp;').replace(/"/g, '&quot;')
    .replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

/**
 * Normalize config.basePath into an absolute, no-trailing-slash prefix.
 * "" / undefined / "/" → "" (served at root, page-relative — unchanged).
 * "brand" or "/brand/" → "/brand".
 */
function normalizeBasePath(bp) {
  if (!bp || typeof bp !== 'string') return '';
  var s = bp.trim();
  if (!s) return '';
  // Exactly one leading slash: collapse "//brand" (a protocol-relative URL —
  // browsers read it as a cross-origin host) and "brand" alike to "/brand".
  s = '/' + s.replace(/^\/+/, '');
  s = s.replace(/\/+$/, '');
  return s;
}

/**
 * Generate a Google Fonts <link> tag from config.fonts.
 */
function generateFontsLink(config) {
  if (!config.fonts) return '';
  var families = [];
  if (config.fonts.display && config.fonts.display.googleImport) {
    families.push(config.fonts.display.googleImport);
  }
  if (config.fonts.body && config.fonts.body.googleImport) {
    families.push(config.fonts.body.googleImport);
  }
  if (!families.length) return '';
  return '<link href="https://fonts.googleapis.com/css2?family=' +
    families.join('&family=') + '&display=swap" rel="stylesheet">';
}

/**
 * Build production-ready static files from dist/ templates + config.
 * Writes index.html and styles.css into the target directory.
 */
function build(distDir, targetDir, config) {
  // Absolute base path the guide is served from (e.g. "/brand"). Empty = root /
  // page-relative, in which case nothing below is rewritten (byte-identical to
  // the pre-basePath output). The "/" + file form (no trailing slash on basePath)
  // is what lets a framework rewrite like /brand → /brand/index.html resolve.
  var basePath = normalizeBasePath(config.basePath);
  // Build styles.css: append the config :root AFTER the stylesheet's default
  // tokens so brand overrides win the cascade (styles.css ships a baseline
  // :root; an earlier block would be overridden by it).
  var cssTemplate = fs.readFileSync(path.join(distDir, 'styles.css'), 'utf8');
  var rootCSS = generateRootCSS(config);
  var builtCSS = cssTemplate + '\n\n/* Generated by brandkit build — brand overrides */\n' + rootCSS + '\n';
  fs.writeFileSync(path.join(targetDir, 'styles.css'), builtCSS);

  // Agent-native exports: brand.json (semantic), tokens.json (W3C DTCG),
  // brand.md (LLM brief). brandJson is reused to embed the data in the page.
  var exported = exporter.writeExports(config, targetDir, 'all');

  // Build index.html: inject fonts link + title + agent-discoverable brand data
  var htmlTemplate = fs.readFileSync(path.join(distDir, 'index.html'), 'utf8');
  var fontsLink = generateFontsLink(config);
  var brandName = (config.brand && config.brand.displayName) || 'Brand';

  // Inject fonts link + a discovery <link> for the structured brand data.
  // When a basePath is set, prefix the brandkit-generated refs (stylesheet,
  // engine, brand.json) so they resolve from a non-trailing-slash URL; also
  // expose the base to the runtime engine via window.__BRANDKIT_BASE__.
  // The Google Fonts link and author-supplied logo paths are left untouched.
  // basePath is author-controlled config, so it's hardened before it lands in
  // markup, each context with its own escaping:
  //  - inline <script>: JSON.stringify + "<" → <, so a "</script>" in the
  //    value can't break out of the script element (JS-string context).
  //  - href/src attributes: HTML-attribute-escaped (basePathAttr), so a stray
  //    quote can't break out of the attribute and inject a handler.
  //  - all .replace() calls below use function replacers, so a "$" in the path
  //    isn't interpreted as a $-replacement pattern.
  // The Google Fonts link and author-supplied logo paths are left untouched.
  var basePathLiteral = JSON.stringify(basePath).replace(/</g, '\\u003C');
  var basePathAttr = escapeAttr(basePath);
  var brandJsonHref = basePath ? basePathAttr + '/brand.json' : 'brand.json';
  var headInject = (basePath ? '<script>window.__BRANDKIT_BASE__ = ' + basePathLiteral + ';</script>\n' : '') +
    (fontsLink ? fontsLink + '\n' : '') +
    '<link rel="alternate" type="application/json" href="' + brandJsonHref + '" title="Brand data">\n';
  htmlTemplate = htmlTemplate.replace('</head>', function () { return headInject + '</head>'; });

  if (basePath) {
    htmlTemplate = htmlTemplate
      .replace('href="styles.css"', function () { return 'href="' + basePathAttr + '/styles.css"'; })
      .replace('src="engine.js"', function () { return 'src="' + basePathAttr + '/engine.js"'; });
  }

  // Set title
  htmlTemplate = htmlTemplate.replace(
    '<title>Brand Guide</title>',
    '<title>' + brandName + ' \u2014 Brand Guide</title>'
  );

  // Embed brand.json inline so an agent that fetches the page gets structured
  // brand data with zero extra requests or scraping. Every "<" is escaped to
  // its JSON unicode form (<, which JSON.parse restores to "<"), so no
  // config value can produce a "</script" sequence and break out of the block.
  if (exported.brandJson) {
    var embedded = JSON.stringify(exported.brandJson).replace(/</g, '\\u003C');
    var embed = '<script type="application/json" id="brandkit-brand">' + embedded + '</script>\n';
    htmlTemplate = htmlTemplate.replace('</body>', embed + '</body>');
  }

  fs.writeFileSync(path.join(targetDir, 'index.html'), htmlTemplate);

  // Copy engine.js as-is
  fs.copyFileSync(
    path.join(distDir, 'engine.js'),
    path.join(targetDir, 'engine.js')
  );

  return exported;
}

module.exports = {
  generateRootCSS: generateRootCSS,
  generateFontsLink: generateFontsLink,
  normalizeBasePath: normalizeBasePath,
  build: build
};
