var fs = require('fs');
var path = require('path');
var exporter = require('./export');

/**
 * Generate a :root CSS block from config.theme + config.fonts.
 */
function generateRootCSS(config) {
  var lines = [':root {'];
  if (config.theme) {
    var keys = Object.keys(config.theme);
    for (var i = 0; i < keys.length; i++) {
      lines.push('  ' + keys[i] + ': ' + config.theme[keys[i]] + ';');
    }
  }
  if (config.fonts) {
    if (config.fonts.display) {
      lines.push("  --font-display: '" + config.fonts.display.family + "', sans-serif;");
    }
    if (config.fonts.body) {
      lines.push("  --font-body: '" + config.fonts.body.family + "', sans-serif;");
    }
  }
  lines.push('}');
  return lines.join('\n');
}

/**
 * Generate a Google Fonts <link> tag from config.fonts.
 */
function generateFontsLink(config) {
  if (!config.fonts) return '';
  var families = [];
  if (config.fonts.display && config.fonts.display.googleImport) {
    families.push(config.fonts.display.googleImport);
  }
  if (config.fonts.body && config.fonts.body.googleImport) {
    families.push(config.fonts.body.googleImport);
  }
  if (!families.length) return '';
  return '<link href="https://fonts.googleapis.com/css2?family=' +
    families.join('&family=') + '&display=swap" rel="stylesheet">';
}

/**
 * Build production-ready static files from dist/ templates + config.
 * Writes index.html and styles.css into the target directory.
 */
function build(distDir, targetDir, config) {
  // Build styles.css: append the config :root AFTER the stylesheet's default
  // tokens so brand overrides win the cascade (styles.css ships a baseline
  // :root; an earlier block would be overridden by it).
  var cssTemplate = fs.readFileSync(path.join(distDir, 'styles.css'), 'utf8');
  var rootCSS = generateRootCSS(config);
  var builtCSS = cssTemplate + '\n\n/* Generated by brandkit build — brand overrides */\n' + rootCSS + '\n';
  fs.writeFileSync(path.join(targetDir, 'styles.css'), builtCSS);

  // Agent-native exports: brand.json (semantic), tokens.json (W3C DTCG),
  // brand.md (LLM brief). brandJson is reused to embed the data in the page.
  var exported = exporter.writeExports(config, targetDir, 'all');

  // Build index.html: inject fonts link + title + agent-discoverable brand data
  var htmlTemplate = fs.readFileSync(path.join(distDir, 'index.html'), 'utf8');
  var fontsLink = generateFontsLink(config);
  var brandName = (config.brand && config.brand.displayName) || 'Brand';

  // Inject fonts link + a discovery <link> for the structured brand data
  var headInject = (fontsLink ? fontsLink + '\n' : '') +
    '<link rel="alternate" type="application/json" href="brand.json" title="Brand data">\n';
  htmlTemplate = htmlTemplate.replace('</head>', headInject + '</head>');

  // Set title
  htmlTemplate = htmlTemplate.replace(
    '<title>Brand Guide</title>',
    '<title>' + brandName + ' \u2014 Brand Guide</title>'
  );

  // Embed brand.json inline so an agent that fetches the page gets structured
  // brand data with zero extra requests or scraping. Every "<" is escaped to
  // its JSON unicode form (<, which JSON.parse restores to "<"), so no
  // config value can produce a "</script" sequence and break out of the block.
  if (exported.brandJson) {
    var embedded = JSON.stringify(exported.brandJson).replace(/</g, '\\u003C');
    var embed = '<script type="application/json" id="brandkit-brand">' + embedded + '</script>\n';
    htmlTemplate = htmlTemplate.replace('</body>', embed + '</body>');
  }

  fs.writeFileSync(path.join(targetDir, 'index.html'), htmlTemplate);

  // Copy engine.js as-is
  fs.copyFileSync(
    path.join(distDir, 'engine.js'),
    path.join(targetDir, 'engine.js')
  );

  return exported;
}

module.exports = {
  generateRootCSS: generateRootCSS,
  generateFontsLink: generateFontsLink,
  build: build
};
